### PR TITLE
Bagdes and test coverage

### LINKED ISSUE #1: Add badges and test coverages
Improve the output of the unit tests with badges on the main page.
Add also test coverage metrics.

### PR DESCRIPTION
**Pull request by FabienDanieau**
*Draft pull request for triggering the workflow*

### CODE REVIEW

**Comment by FabienDanieau** [comment]
Test coverage has been added to the github actions. Report is directly displayed in the pull request and the actions. HTML report can be downloaded as well.

Badges are also generated and displayed in the README.md

**Comment by RemiFabre** [comment]
I read the README, cloned the repo and ran the tests and coverage scripts. Nice work!
The gitflow page from bitbucket seems better than the one from github.

I believe there should be a small section on what should be in the README.md of a repo (maybe add a template somewhere?), with at least the procedure to install, run and test the code. This should also be present in this repo's README. For example I had to :
pip3 install -r requirements.txt
pip3 install lark


Also it would be nice to add a small section on the usage of virtual environments. I use this:
https://virtualenvwrapper.readthedocs.io/en/latest/
No need to write a whole guide on this, a 1 liner with this link (for example) seems enough.

In fact, this repository currently does 2 things:
- Explain what the good practices are
- Give an example of said good practices
 It should be cristal clear what a developper must do to start a new repository. Should someone clone this repo and then change stuff by hand? Maybe we should have a "skeleton" repo, that would be similar to this one, but meant to be the starter point of any empty Python repo. Of course, that skeleton repository would be linked here so any developper reading this would know where to start. Do you agree?

**Comment by pierre-rouanet** [comment]
> Maybe we should have a "skeleton" repo, that would be similar to this one, but meant to be the starter point of any empty Python repo. Of course, that skeleton repository would be linked here so any developper reading this would know where to start. Do you agree?
You can use [GitHub template repo](https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-template-repository) for that

**Comment by FabienDanieau** [comment]
> You can use [GitHub template repo](https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-template-repository) for that

I cannot make this repo a template since there is LFS files. I can remove them (there's just the image) if we want to do this but we'll lost the example. What do you prefer?

**Comment by FabienDanieau** [comment]
> I believe there should be a small section on what should be in the README.md of a repo (maybe add a template somewhere?), with at least the procedure to install, run and test the code. This should also be present in this repo's README. For example I had to : pip3 install -r requirements.txt pip3 install lark

Yes I'll make a new issue for that (#5)
> 
> Also it would be nice to add a small section on the usage of virtual environments. I use this: https://virtualenvwrapper.readthedocs.io/en/latest/ No need to write a whole guide on this, a 1 liner with this link (for example) seems enough.

Sure I use conda on my side. It is definitely something we should be aligned on. See issue (#6)

**Comment by RemiFabre** [comment]
> > You can use [GitHub template repo](https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-template-repository) for that
> 
> I cannot make this repo a template since there is LFS files. I can remove them (there's just the image) if we want to do this but we'll lost the example. What do you prefer?

I dont have a strong opinion on this, but I believe it would be best to have 2 separate repositories: 
- This one, that explains the python coding guidelines and gives useful links/guides/ressources
- Another one that is meant to be used as a template. Of course, the guideline repository would have a link to the template repository

If you create an issue on this, I'll merge this PR as you've adressed the other issues (by creating issues :) )

**Comment by FabienDanieau** [comment]
> If you create an issue on this, I'll merge this PR as you've adressed the other issues (by creating issues :) )

I created issue #7 . I'll think about the best way to do this, so we don't have synchronize too many things between two repos if we go with this solution.

**Review by RemiFabre — APPROVED** [review]

**Comment by RemiFabre** [comment]
Ok, merging

**Pull request merged**
